# Generated by Django 4.1.1 on 2024-01-04 10:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=30, verbose_name='Notification Heading')),
                ('content', models.CharField(max_length=200, verbose_name='Notification Content')),
                ('viewed', models.BooleanField(default=False, verbose_name='Notification Viewed')),
                ('status', models.BooleanField(default=True, verbose_name='Notification Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Notification Created On')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Notification Last Updated')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Notification Management',
            },
        ),
    ]
