# Generated by Django 4.1.1 on 2024-01-11 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_remove_notification_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_count', models.IntegerField(default=0, verbose_name='Project Count')),
                ('client_count', models.IntegerField(default=0, verbose_name='Client Count')),
            ],
            options={
                'verbose_name_plural': 'Notification Statistics',
            },
        ),
    ]
