# Generated by Django 4.2.3 on 2024-02-21 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_id', models.CharField(max_length=250, unique=True)),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'db_table': 'tblClient',
            },
        ),
        migrations.CreateModel(
            name='DataFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_code', models.CharField(max_length=250)),
                ('table', models.CharField(blank=True, max_length=250, null=True)),
                ('view', models.CharField(blank=True, max_length=250, null=True)),
                ('type', models.CharField(choices=[('collar', 'Collar'), ('point', 'Point')], max_length=10)),
                ('file_name', models.CharField(max_length=250)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dmirs.client')),
            ],
            options={
                'db_table': 'tblDatafile',
                'ordering': ['id'],
                'unique_together': {('header_code', 'client')},
            },
        ),
        migrations.CreateModel(
            name='MetaHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_code', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=250)),
                ('default_value', models.CharField(default=None, max_length=250)),
                ('sql_code', models.CharField(default=None, max_length=250)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dmirs.client')),
            ],
            options={
                'db_table': 'tblHeader',
                'unique_together': {('header_code', 'client')},
            },
        ),
        migrations.CreateModel(
            name='DataFileHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dmirs.client')),
                ('data_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='headers', to='dmirs.datafile')),
                ('header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dmirs.metaheader')),
            ],
            options={
                'db_table': 'tblDatafileHeader',
                'unique_together': {('data_file', 'header', 'client')},
            },
        ),
        migrations.CreateModel(
            name='DataFileColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_name', models.CharField(max_length=250)),
                ('alias', models.CharField(max_length=250)),
                ('order', models.IntegerField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dmirs.client')),
                ('data_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='dmirs.datafile')),
            ],
            options={
                'db_table': 'tblDatafileColumn',
                'unique_together': {('column_name', 'data_file', 'client')},
            },
        ),
    ]
