# Generated by Django 4.2.3 on 2024-02-15 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_id', models.CharField(max_length=250, unique=True)),
                ('name', models.CharField(max_length=250, unique=True)),
            ],
            options={
                'db_table': 'tblClient',
            },
        ),
        migrations.CreateModel(
            name='Headers',
            fields=[
                ('header_code', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=250)),
                ('default_value', models.CharField(default=None, max_length=250)),
                ('sql_code', models.CharField(default=None, max_length=250)),
            ],
            options={
                'db_table': 'tblLIBReportHeader',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_code', models.CharField(max_length=250)),
                ('default_table', models.CharField(blank=True, max_length=250, null=True)),
                ('description', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'tblLIBReport',
            },
        ),
    ]
