# Generated by Django 4.2.3 on 2024-02-19 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_id', models.CharField(max_length=250, unique=True)),
                ('name', models.CharField(max_length=250, unique=True)),
            ],
            options={
                'db_table': 'tblClient',
            },
        ),
        migrations.CreateModel(
            name='DataFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_code', models.CharField(max_length=250)),
                ('default_table', models.CharField(blank=True, max_length=250, null=True)),
                ('default_view', models.CharField(blank=True, max_length=250, null=True)),
                ('file_name', models.CharField(max_length=250)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dmirs.clientdb')),
            ],
            options={
                'db_table': 'tblDatafile',
            },
        ),
        migrations.CreateModel(
            name='MetaHeader',
            fields=[
                ('header_code', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=250)),
                ('default_value', models.CharField(default=None, max_length=250)),
                ('sql_code', models.CharField(default=None, max_length=250)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dmirs.clientdb')),
            ],
            options={
                'db_table': 'tblLIBHeader',
            },
        ),
        migrations.CreateModel(
            name='DataFileColumns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_name', models.CharField(max_length=250)),
                ('alias', models.CharField(max_length=250)),
                ('order', models.IntegerField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dmirs.clientdb')),
                ('data_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='dmirs.datafile')),
            ],
            options={
                'db_table': 'tblDatafileColumn',
            },
        ),
        migrations.CreateModel(
            name='DataFileHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dmirs.clientdb')),
                ('data_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dmirs.datafile')),
                ('header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dmirs.metaheader')),
            ],
            options={
                'db_table': 'tblDatafileHeader',
                'unique_together': {('data_file', 'header')},
            },
        ),
    ]
