# Generated by Django 4.2.3 on 2024-02-19 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dmirs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='metaheader',
            table='tblHeader',
        ),
    ]
