# Generated by Django 4.2.3 on 2024-02-20 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dmirs', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DataFileColumns',
            new_name='DataFileColumn',
        ),
        migrations.AlterModelOptions(
            name='datafile',
            options={'ordering': ['id']},
        ),
    ]
