# Generated by Django 4.2.3 on 2024-02-15 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dmirs', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Report',
            new_name='DataFile',
        ),
        migrations.RenameModel(
            old_name='Headers',
            new_name='MetaHeader',
        ),
        migrations.RenameField(
            model_name='datafile',
            old_name='description',
            new_name='file_name',
        ),
    ]
