# Generated by Django 4.2.3 on 2024-02-26 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmirs', '0002_remove_datafile_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafile',
            name='meta_headers',
            field=models.ManyToManyField(through='dmirs.DataFileHeader', to='dmirs.metaheader'),
        ),
    ]
