# Generated by Django 4.2.3 on 2024-02-19 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmirs', '0002_alter_metaheader_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdb',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
