# Generated by Django 4.2.3 on 2024-02-16 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dmirs', '0004_databaseobject_datatable_datafile_default_view_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataFileHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('data_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dmirs.datafile')),
                ('header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dmirs.metaheader')),
            ],
            options={
                'db_table': 'tblDatafileHeader',
                'unique_together': {('data_file', 'header')},
            },
        ),
        migrations.AddField(
            model_name='datafile',
            name='headers',
            field=models.ManyToManyField(related_name='tblDatafileHeader', through='dmirs.DataFileHeader', to='dmirs.metaheader'),
        ),
    ]
