# Use an official Python runtime as a parent image
FROM python:3.10

RUN apt-get update && apt-get install -y build-essential

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN pip install --upgrade pip

# Copy the entrypoint script into the container
COPY docker/celery_beat/entrypoint.sh /

# Set execute permissions for the entrypoint script
RUN chmod +x entrypoint.sh

# Set the working directory in the container
WORKDIR /app
#
# # Copy the requirements file into the container
COPY src/requirements.txt /app/
#
# # Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt

# Use the APP_ENVIRONMENT variable
ENV DJANGO_ENV=${APP_ENVIRONMENT}



# Set the entrypoint
ENTRYPOINT ["/entrypoint.sh"]